version: '3.9'

x-php-config:
  &php-config
  env_file:
    - .env
  build:
    context: .
    args:
      user: www
      uid: 80

services:
  migrations:
    <<: *php-config
    command: "./index.php migrate"
    depends_on:
      mysql:
        condition: service_healthy

  telegram-updates:
    <<: *php-config
    command: sh -c "while true; do ./index.php get-telegram-updates; done"
    depends_on:
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  ton-dns-load-new-bets:
    <<: *php-config
    command: sh -c "while true; do ./index.php load-new-bets; sleep 1; done"
    depends_on:
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  ton-dns-load-auctions:
    <<: *php-config
    command: sh -c "while true; do ./index.php load-auctions; sleep 1; done"
    depends_on:
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "${MYSQL_HOST}" ]